### ISSUE TITLE
Getting this exception on Redmine 3.3

### ISSUE THREAD

**Issue by oko-x** [ste26054/redmine_leaves_holidays#54]
Redmine. Error 500

Global error
PG::UndefinedFunction: ERROR: function datediff(date, unknown) does not exist LINE 1: ...D ("leave_requests"."request_status" != $4) AND ((DATEDIFF(f... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. : SELECT "leave_requests".\* FROM "leave_requests" INNER JOIN "users" ON "users"."id" = "leave_requests"."user_id" AND "users"."type" IN ('User', 'AnonymousUser') WHERE "users"."status" = $1 AND ("leave_requests"."request_status" != $2) AND "leave_requests"."user_id" = $3 AND (1=1) AND ("leave_requests"."request_status" != $4) AND ((DATEDIFF(from_date, '2017-08-31') \* DATEDIFF('2016-09-01', to_date)) >= 0) AND "leave_requests"."is_informational" = $5 ORDER BY "leave_requests"."id" ASC LIMIT 1000 

Back  

Error log

```
    /home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare'
```

/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare_statement'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in`exec_cache'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in`exec_query'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in`select_all'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `block in select_all'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:83:in`cache_sql'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:68:in `select_all'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/querying.rb:39:in`find_by_sql'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:639:in `exec_queries'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:515:in`load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation.rb:243:in `to_a'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:117:in`find_in_batches'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/batches.rb:50:in `find_each'
/home/redmine/redmine/plugins/redmine_leaves_holidays/lib/redmine_leaves_holidays/leaves_holidays_dates.rb:90:in`total_leave_days_remaining'
/home/redmine/redmine/plugins/redmine_leaves_holidays/lib/redmine_leaves_holidays/patches/user_patch.rb:150:in `days_remaining'
/home/redmine/redmine/plugins/redmine_leaves_holidays/app/controllers/leave_requests_controller.rb:39:in`index'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:198:in`process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:20:in`block in process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:498:in`block (2 levels) in around'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:313:in`block (2 levels) in halting'
/home/redmine/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:432:in`block in make_lambda'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:312:in`block in halting'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:497:in`block in around'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in`_run_process_action_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb:19:in`process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:32:in`block in process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `block in instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:164:in `instrument'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb:30:in`process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb:137:in `process'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionview-4.2.6/lib/action_view/rendering.rb:30:in`process'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:196:in `dispatch'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb:237:in `block in action'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:43:in`serve'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in`each'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/head.rb:13:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in`context'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/query_cache.rb:36:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in`__run_callbacks__'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in`run_callbacks'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:38:in `call_app'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in`block in call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in`tagged'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:165:in`call'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in`method_missing'
/home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
/home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in`worker_loop'
/home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/home/redmine/data/tmp/bundle/ruby/2.1.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in`start'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in`load'
/home/redmine/redmine/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'

**Comment by oko-x** [comment]
I would be undyingly grateful for this plugin availability on 3.3, if you have some time to point me to the right direction I am glad to help.

**Comment by ste26054** [comment]
The plugin was developed using MySQL adapter. Hence, I think the error is due to the function `DATEDIFF` which does not exist in PostgreSQL. I am not familiar with this platform, but if you do the problem is located [here](https://github.com/ste26054/redmine_leaves_holidays/blob/b2c82f15d70e2cb70ca43940b43280b70f6be7af/app/models/leave_request.rb#L53)

**Comment by oko-x** [comment]
I created a pull request with fix. Thank You for the assistance. #55
